[profile.release]
panic = 'unwind'

[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.1'
hex-literal = '0.1'
log = '0.4'
parity-codec = '3.2'
parking_lot = '0.7.1'
tokio = '0.1'
trie-root = '0.12.0'

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.template-node-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = 'dec7af1cf40ceb7a57537e85af27dc9e18ff2fd5'

[build-dependencies]
vergen = '3'

[package]
authors = ['Parity Technologies <admin@parity.io>']
build = 'build.rs'
edition = '2018'
name = 'template-node'
version = '1.0.0'

[[bin]]
name = 'template-node'
path = 'src/main.rs'
